//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSTCarRental.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class TBLARABA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLARABA()
        {
            this.TBLKIRALA = new HashSet<TBLKIRALA>();
        }
    
        public int ID { get; set; }
        public Nullable<byte> KATEGORI { get; set; }
        public string ARABAISIM { get; set; }
        [AllowHtml]
        public string ARABADETAY { get; set; }
        public Nullable<int> ARABAFIYAT { get; set; }
        public string PLAKA { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string RESIM { get; set; }
    
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKIRALA> TBLKIRALA { get; set; }
    }
}
