//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSTCarRental.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLILETISIMGEC
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string MAIL { get; set; }
        public string PHONE { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    }
}
